base_url = "https://yongcaoplus.github.io/c3nlp/"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
title = {tagline = "NAACL 2025 Workshop", title = C3NLP", subtitles = ["Albuquerque, New Mexico", "May 04, 2025"]}
banner = {extension = "svg", size = "fixed", fade = true}
buttons = [{name = "Register", url = "#"}, {name="Submit Paper", url="https://openreview.net/"}]
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"}]