name = "Academic Workshop"
description = "A Zola theme for a website to list the schedule of your scientific workshop or seminar series"
license = "MIT"
homepage = "https://github.com/aterenin/academic-workshop"
min_version = "0.18.0"
demo = "https://aterenin.github.io/academic-workshop"

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme, which is [designed to last](https://jeffhuang.com/designed_to_last/)."
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10

[author]
name = "Alexander Terein"
homepage = "https://avt.im"